// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzkcPJpuCF9ZgMeQFC67zZ0UqAivGKyE',
    appId: '1:847178421801:web:61d1b078354543d356ae38',
    messagingSenderId: '847178421801',
    projectId: 'test-d439d',
    authDomain: 'test-d439d.firebaseapp.com',
    databaseURL: 'https://test-d439d-default-rtdb.firebaseio.com',
    storageBucket: 'test-d439d.appspot.com',
    measurementId: 'G-QJEZEFZ1NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlccfmmsYStU8NI_nZ_DjnnXkjNc_aJE',
    appId: '1:847178421801:android:d480cfa9936cf17e56ae38',
    messagingSenderId: '847178421801',
    projectId: 'test-d439d',
    databaseURL: 'https://test-d439d-default-rtdb.firebaseio.com',
    storageBucket: 'test-d439d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe8KjGKqX71pMrh1X3JUleEKAgjtksxx4',
    appId: '1:847178421801:ios:c69645c855ab5bd456ae38',
    messagingSenderId: '847178421801',
    projectId: 'test-d439d',
    databaseURL: 'https://test-d439d-default-rtdb.firebaseio.com',
    storageBucket: 'test-d439d.appspot.com',
    iosBundleId: 'com.example.testForArgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe8KjGKqX71pMrh1X3JUleEKAgjtksxx4',
    appId: '1:847178421801:ios:c69645c855ab5bd456ae38',
    messagingSenderId: '847178421801',
    projectId: 'test-d439d',
    databaseURL: 'https://test-d439d-default-rtdb.firebaseio.com',
    storageBucket: 'test-d439d.appspot.com',
    iosBundleId: 'com.example.testForArgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUzkcPJpuCF9ZgMeQFC67zZ0UqAivGKyE',
    appId: '1:847178421801:web:375f3756dc92944b56ae38',
    messagingSenderId: '847178421801',
    projectId: 'test-d439d',
    authDomain: 'test-d439d.firebaseapp.com',
    databaseURL: 'https://test-d439d-default-rtdb.firebaseio.com',
    storageBucket: 'test-d439d.appspot.com',
    measurementId: 'G-3NGWJZCHZC',
  );

}